влияние датчиков на лифт
ivanbukhtiyarov/elevators pull request #32
Opened 2021-05-16 10:26 UTC by AVMer

2021-05-16 11:16 UTC, alexander135 approved these changes

2021-05-16 11:17 UTC, JellyBongo requested changes

2021-05-16 11:17 UTC, JellyBongo commented on src/elevator.py
> +        self.close_doors()
МБ, это просто как поле оформить? Прост очередной датчик.

2021-05-16 22:33 UTC, qpep3b commented
тесты падают. Не добро

2021-06-01 19:44 UTC, JellyBongo approved these changes

2021-06-01 19:45 UTC, merged